kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-home"
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
