apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-master"
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: master
