apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-master"
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: master
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 50000
      protocol: TCP
      name: slave
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: master
