apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: sample
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
